"""Render all compiled domain programs as one content-addressed artifact."""

from __future__ import annotations

import hashlib
import json
import keyword
import re
import runpy
import shutil
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from pathlib import Path

COMPILED_WIRE_ARTIFACT_SCHEMA_VERSION = 5
COMPILED_WIRE_RENDERER_ABI = 15
_ARTIFACT_DIGEST_DOMAIN = b"dsctl-compiled-wire-artifact-v5\0"
_MODULE_NAME = re.compile(r"[a-z_][a-z0-9_]*\Z")
_PACKAGE_INITIALIZER = "from __future__ import annotations\n"
_RESERVED_MODULE_PARTS = frozenset({"__init__", "__pycache__", "_manifest"})


@dataclass(frozen=True)
class CompiledWireModule:
    """One generated domain or support module collected before rendering."""

    name: str
    content: str
    kind: Literal["domain", "support"]


def render_compiled_wire_artifact(
    modules: tuple[CompiledWireModule, ...],
    output_root: Path,
) -> None:
    """Write one complete package and manifest for all compiled domains."""
    ordered = tuple(sorted(modules, key=lambda item: item.name))
    if not ordered or len({item.name for item in ordered}) != len(ordered):
        message = "compiled wire modules must be nonempty and uniquely named"
        raise ValueError(message)
    if not any(module.kind == "domain" for module in ordered):
        message = "compiled wire artifact must contain at least one domain module"
        raise ValueError(message)
    module_paths, package_paths = _module_paths(ordered)
    contents = {"__init__.py": _PACKAGE_INITIALIZER}
    contents.update(
        (f"{package}/__init__.py", _PACKAGE_INITIALIZER) for package in package_paths
    )
    contents.update((module_paths[module.name], module.content) for module in ordered)

    package_root = output_root / "generated" / "wire_programs"
    if package_root.exists():
        shutil.rmtree(package_root)
    package_root.mkdir(parents=True)
    for relative_path, content in sorted(contents.items()):
        path = package_root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    artifact_modules = tuple(sorted(contents))
    domain_modules = tuple(
        sorted(
            module_paths[module.name] for module in ordered if module.kind == "domain"
        )
    )
    support_modules = tuple(
        sorted(set(artifact_modules).difference({"__init__.py", *domain_modules}))
    )
    runtime_manifest_path = output_root / "generated" / "wire_runtime" / "_manifest.py"
    runtime_manifest = runpy.run_path(str(runtime_manifest_path))
    runtime_digest = runtime_manifest.get("CONTENT_DIGEST")
    if not isinstance(runtime_digest, str):
        message = "generated wire runtime manifest has no content digest"
        raise TypeError(message)
    content_digest = _module_content_digest(package_root, artifact_modules)
    (package_root / "_manifest.py").write_text(
        _render_manifest(
            modules=artifact_modules,
            domain_modules=domain_modules,
            support_modules=support_modules,
            content_digest=content_digest,
            runtime_digest=runtime_digest,
        ),
        encoding="utf-8",
    )


def _module_paths(
    modules: tuple[CompiledWireModule, ...],
) -> tuple[dict[str, str], set[str]]:
    paths: dict[str, str] = {}
    packages: set[str] = set()
    for module in modules:
        parts = module.name.split(".")
        if (
            module.kind not in {"domain", "support"}
            or (module.kind == "domain" and len(parts) != 1)
            or not module.content
            or any(
                _MODULE_NAME.fullmatch(part) is None
                or keyword.iskeyword(part)
                or part in _RESERVED_MODULE_PARTS
                for part in parts
            )
        ):
            message = f"compiled wire module is invalid: {module.name!r}"
            raise ValueError(message)
        paths[module.name] = f"{'/'.join(parts)}.py"
        packages.update("/".join(parts[:index]) for index in range(1, len(parts)))
    collisions = {path.removesuffix(".py") for path in paths.values()} & packages
    if collisions:
        message = (
            "compiled wire modules conflict with support packages: "
            f"{sorted(collisions)!r}"
        )
        raise ValueError(message)
    return paths, packages


def _render_manifest(
    *,
    modules: tuple[str, ...],
    domain_modules: tuple[str, ...],
    support_modules: tuple[str, ...],
    content_digest: str,
    runtime_digest: str,
) -> str:
    return "\n".join(
        (
            "from __future__ import annotations",
            "",
            "# Generated by tools/generate_ds_runtime_bundles.py; do not edit.",
            (
                "COMPILED_WIRE_ARTIFACT_SCHEMA_VERSION = "
                f"{COMPILED_WIRE_ARTIFACT_SCHEMA_VERSION}"
            ),
            f"RENDERER_ABI = {COMPILED_WIRE_RENDERER_ABI}",
            "MODULES = (",
            *(f"    {json.dumps(module)}," for module in modules),
            ")",
            "DOMAIN_MODULES = (",
            *(f"    {json.dumps(module)}," for module in domain_modules),
            ")",
            "SUPPORT_MODULES = (",
            *(f"    {json.dumps(module)}," for module in support_modules),
            ")",
            f"CONTENT_DIGEST = {json.dumps(content_digest)}",
            f"WIRE_RUNTIME_CONTENT_DIGEST = {json.dumps(runtime_digest)}",
            "",
        )
    )


def _module_content_digest(package_root: Path, modules: tuple[str, ...]) -> str:
    digest = hashlib.sha256()
    digest.update(_ARTIFACT_DIGEST_DOMAIN)
    for module in modules:
        digest.update(module.encode("utf-8"))
        digest.update(b"\0")
        digest.update((package_root / module).read_bytes())
        digest.update(b"\0")
    return f"sha256:{digest.hexdigest()}"


__all__ = [
    "CompiledWireModule",
    "render_compiled_wire_artifact",
]
