"""Compile reviewed compatibility decisions into exact materialized profiles."""

from __future__ import annotations

import copy
import hashlib
import json
import re
from dataclasses import asdict, dataclass
from dataclasses import field as dataclass_field
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

from ds_codegen.compatibility_impact import (
    READ_OPERATION_BINDINGS,
    RUNTIME_OPERATION_BINDINGS,
    EvidenceSource,
    ReviewedBinding,
    SelectorSemantics,
    WireTypeRef,
    validate_reviewed_bindings,
)
from ds_codegen.profile_ledger import (
    DEFAULT_VERSION_PROFILE_LEDGER,
    exact_versions,
    load_version_profile_ledger,
    reviewed_profile_versions,
    select_exact_versions,
)

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

GENERATED_VERSION_PROFILE_PATH = Path("generated/version_profiles.py")
PROFILE_SCHEMA_VERSION = 1

_AVAILABILITIES = frozenset({"supported", "limited", "unsupported"})
_BUILD_STATUSES = frozenset({"accepted", "pending", "blocked"})
_EXECUTION_MODES = frozenset(
    {
        "not_executable",
        "local",
        "diagnostic_recipe",
        "legacy_adapter",
        "generated_adapter",
        "wire_program",
    }
)
_VERIFICATIONS = frozenset({"static", "contract_tested", "live_smoke", "live_full"})
_SUPPORT_LEVELS = frozenset({"full", "legacy_core", "experimental"})
_FINGERPRINT_AXES = (
    "source",
    "effective_wire",
    "consumed_projection",
    "preservation",
)
_SHA256 = re.compile(r"sha256:[0-9a-f]{64}\Z")
_GIT_OBJECT = re.compile(r"[0-9a-f]{40}\Z")
_TERMINAL_UNAVAILABLE_REASONS = frozenset(
    {"upstream_capability_absent", "upstream_capability_limited"}
)
_WIRE_PRESENT_RUNTIME_LIMITATION = "upstream_runtime_limited"


def compute_fingerprints(
    *,
    source: object,
    effective_wire: object,
    consumed_projection: object,
    preservation: object,
) -> dict[str, str]:
    """Hash four independent contracts without cross-axis coupling."""
    inputs = {
        "source": source,
        "effective_wire": effective_wire,
        "consumed_projection": consumed_projection,
        "preservation": preservation,
    }
    return {
        axis: _fingerprint({"axis": axis, "contract": inputs[axis]})
        for axis in _FINGERPRINT_AXES
    }


def compile_version_profile_data(
    *,
    stable_actions: Iterable[str],
    ledger: Mapping[str, object] | None = None,
    versions: Iterable[str] | None = None,
) -> dict[str, Any]:
    """Materialize every exact version/action coordinate from reviewed facts."""
    actions = tuple(sorted(_stable_action_set(stable_actions)))
    loaded_ledger = (
        load_version_profile_ledger() if ledger is None else copy.deepcopy(dict(ledger))
    )
    _validate_ledger(loaded_ledger, stable_actions=frozenset(actions))
    selected = select_exact_versions(
        reviewed_profile_versions(loaded_ledger),
        versions,
        label="version profile ledger",
    )
    select_exact_versions(
        READ_OPERATION_BINDINGS, selected, label="reviewed read bindings"
    )
    select_exact_versions(
        RUNTIME_OPERATION_BINDINGS, selected, label="reviewed runtime bindings"
    )
    validate_reviewed_bindings(
        {version: READ_OPERATION_BINDINGS[version] for version in selected}
    )
    validate_reviewed_bindings(
        {version: RUNTIME_OPERATION_BINDINGS[version] for version in selected}
    )

    profiles = {
        version: _compile_profile(
            version,
            actions=actions,
            ledger=loaded_ledger,
        )
        for version in selected
    }
    return {
        "schema_version": PROFILE_SCHEMA_VERSION,
        "target_versions": list(selected),
        "stable_actions": list(actions),
        "profiles": profiles,
    }


def render_version_profiles(data: Mapping[str, object]) -> str:
    """Render named shared records without changing exact profile membership."""
    payload = json.dumps(_shared_render_data(data), ensure_ascii=False, indent=2)
    return "\n".join(
        (
            "# ruff: noqa: E501",
            "from __future__ import annotations",
            "",
            "import copy as _copy",
            "import json as _json",
            "",
            "# Generated by tools/generate_ds_runtime_bundles.py; do not edit.",
            "# Record names identify first occurrence, not inherited version support.",
            "# Each exact binding expands to an independent mutable value.",
            "_PROFILE_JSON = r'''",
            payload,
            "'''",
            "_SHARED_DATA = _json.loads(_PROFILE_JSON)",
            "PROFILE_SCHEMA_VERSION = _SHARED_DATA['schema_version']",
            "TARGET_DS_VERSIONS = tuple(_SHARED_DATA['target_versions'])",
            "STABLE_ACTIONS = tuple(_SHARED_DATA['stable_actions'])",
            "_CAPABILITY_RECORDS = _SHARED_DATA['capability_records']",
            "_BUILD_RECORDS = _SHARED_DATA['build_records']",
            "_BUILD_FIELDS = _SHARED_DATA['build_fields']",
            "",
            "VERSION_PROFILES = {}",
            "for _version in TARGET_DS_VERSIONS:",
            "    _bindings = _SHARED_DATA['profile_bindings'][_version]",
            "    _profile = _copy.deepcopy(_SHARED_DATA['profile_metadata'][_version])",
            "    _profile['actions'] = {",
            "        _action: _copy.deepcopy(_CAPABILITY_RECORDS[_record])",
            "        for _action, _record in _bindings['actions'].items()",
            "    }",
            "    _decisions = {}",
            "    for _operation, _record in _bindings['build_decisions'].items():",
            "        _decision = _copy.deepcopy(_BUILD_RECORDS[_record])",
            "        for _field, _records in _BUILD_FIELDS.items():",
            "            _decision[_field] = _copy.deepcopy(",
            "                _records[_decision[_field]]",
            "            )",
            "        _decisions[_operation] = _decision",
            "    _profile['build_decisions'] = _decisions",
            "    VERSION_PROFILES[_version] = _profile",
            "",
            "PROFILE_DATA = {",
            "    'schema_version': PROFILE_SCHEMA_VERSION,",
            "    'target_versions': list(TARGET_DS_VERSIONS),",
            "    'stable_actions': list(STABLE_ACTIONS),",
            "    'profiles': VERSION_PROFILES,",
            "}",
            "",
        )
    )


@dataclass
class _NamedRecords:
    """Share equal complete values under their first readable source coordinate."""

    values: dict[str, object] = dataclass_field(default_factory=dict)
    names_by_value: dict[str, str] = dataclass_field(default_factory=dict)

    def intern(self, name: str, value: object) -> str:
        key = json.dumps(value, ensure_ascii=False, sort_keys=True)
        existing = self.names_by_value.get(key)
        if existing is not None:
            return existing
        self.names_by_value[key] = name
        self.values[name] = copy.deepcopy(value)
        return name


def _shared_render_data(data: Mapping[str, object]) -> dict[str, object]:
    target_versions = _text_list(
        data.get("target_versions"), label="profile data.target_versions"
    )
    stable_actions = _text_list(
        data.get("stable_actions"), label="profile data.stable_actions"
    )
    _require_profile_data_action_domain(data, stable_actions=stable_actions)
    profiles = _mapping(data.get("profiles"), label="profile data.profiles")
    capabilities = _NamedRecords()
    build_records = _NamedRecords()
    build_fields = {
        field: _NamedRecords()
        for field in (
            "source_operations",
            "type_closure",
            "selector_semantics",
            "evidence_sources",
            "fingerprints",
        )
    }
    profile_bindings: dict[str, object] = {}
    profile_metadata: dict[str, object] = {}
    operations: set[str] | None = None
    operation_actions: dict[str, str] = {}
    for version in target_versions:
        profile = _mapping(profiles[version], label=f"profile data.profiles.{version}")
        actions = _mapping(profile["actions"], label=f"profile {version}.actions")
        decisions = _mapping(
            profile["build_decisions"], label=f"profile {version}.build_decisions"
        )
        if operations is None:
            operations = set(decisions)
        elif set(decisions) != operations:
            message = f"profile {version} has a different build-operation domain"
            raise ValueError(message)
        bindings: dict[str, str] = {}
        for operation, raw_decision in sorted(decisions.items()):
            name = f"{operation}@{version}"
            decision = dict(_mapping(raw_decision, label=f"build decision {name}"))
            _validate_render_decision(operation, decision, operation_actions)
            for field, records in build_fields.items():
                decision[field] = records.intern(name, decision[field])
            bindings[operation] = build_records.intern(name, decision)
        profile_bindings[version] = {
            "actions": {
                action: capabilities.intern(f"{action}@{version}", actions[action])
                for action in stable_actions
            },
            "build_decisions": bindings,
        }
        profile_metadata[version] = {
            key: copy.deepcopy(value)
            for key, value in profile.items()
            if key not in {"actions", "build_decisions"}
        }
    return {
        "schema_version": data["schema_version"],
        "target_versions": target_versions,
        "stable_actions": stable_actions,
        "profile_metadata": profile_metadata,
        "profile_bindings": profile_bindings,
        "capability_records": capabilities.values,
        "build_records": build_records.values,
        "build_fields": {
            field: records.values for field, records in build_fields.items()
        },
    }


def _validate_render_decision(
    operation: str,
    decision: Mapping[str, object],
    operation_actions: dict[str, str],
) -> None:
    if decision.get("semantic_operation") != operation:
        message = f"build decision {operation} declares a different semantic operation"
        raise ValueError(message)
    stable_action = _text(
        decision.get("stable_action"), label=f"build decision {operation}.stable_action"
    )
    if operation_actions.setdefault(operation, stable_action) != stable_action:
        message = f"build decision {operation} changes stable action"
        raise ValueError(message)
    for field in ("build_status", "status_reason"):
        _text(decision.get(field), label=f"build decision {operation}.{field}")
    _text_list(
        decision.get("source_operations"),
        label=f"build decision {operation}.source_operations",
    )
    if "paging_projection" in decision:
        projection = _mapping(
            decision["paging_projection"],
            label=f"build decision {operation}.paging_projection",
        )
        if (
            operation != "task-group.queue.page"
            or set(projection) != {"taskId", "inQueue"}
            or any(type(value) is not bool for value in projection.values())
        ):
            message = f"build decision {operation}.paging_projection is invalid"
            raise ValueError(message)
    _validate_decision_records(operation, decision)
    fingerprints = _mapping(
        decision.get("fingerprints"), label=f"build decision {operation}.fingerprints"
    )
    if set(fingerprints) != set(_FINGERPRINT_AXES):
        message = f"build decision {operation} has invalid fingerprint axes"
        raise ValueError(message)
    for axis, raw_fingerprint in fingerprints.items():
        fingerprint = _text(raw_fingerprint, label=f"{operation}.fingerprints.{axis}")
        if _SHA256.fullmatch(fingerprint) is None:
            message = f"{operation}.fingerprints.{axis} must be a sha256 fingerprint"
            raise ValueError(message)


def _validate_decision_records(operation: str, decision: Mapping[str, object]) -> None:
    record_fields = {
        "type_closure": ("surface", "key"),
        "evidence_sources": ("kind", "reference"),
        "selector_semantics": (
            "resource",
            "consumed_selectors",
            "exposed_identities",
            "native_identity",
            "resolution",
            "parent_identity",
        ),
    }
    for field, keys in record_fields.items():
        label = f"build decision {operation}.{field}"
        for index, raw_record in enumerate(_list(decision.get(field), label=label)):
            record_label = f"{label}[{index}]"
            record = _mapping(raw_record, label=record_label)
            if set(record) != set(keys):
                message = f"{record_label} has invalid fields"
                raise ValueError(message)
            for key in keys:
                if key in {"consumed_selectors", "exposed_identities"}:
                    _text_list(record[key], label=f"{record_label}.{key}")
                elif key != "parent_identity":
                    _text(record[key], label=f"{record_label}.{key}")


def write_version_profiles(
    output_root: Path,
    *,
    stable_actions: Iterable[str],
    ledger: Mapping[str, object] | None = None,
    source_identities: Mapping[str, Mapping[str, str]] | None = None,
    profile_data: Mapping[str, object] | None = None,
    versions: Iterable[str] | None = None,
) -> Path:
    """Write the one generated materialized-profile artifact."""
    stable_action_values = tuple(stable_actions)
    requested_versions = None if versions is None else tuple(versions)
    if source_identities is not None:
        require_version_profile_source_anchors(
            source_identities,
            ledger=ledger,
        )
    output_path = output_root / GENERATED_VERSION_PROFILE_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)
    data = (
        compile_version_profile_data(
            stable_actions=stable_action_values,
            ledger=ledger,
            versions=requested_versions,
        )
        if profile_data is None
        else profile_data
    )
    selected = select_exact_versions(
        reviewed_profile_versions(ledger),
        _text_list(data.get("target_versions"), label="profile data.target_versions"),
        label="version profile ledger",
    )
    if requested_versions is not None and selected != requested_versions:
        message = "precompiled profile target_versions do not match selected versions"
        raise ValueError(message)
    if source_identities is not None and set(source_identities) != set(selected):
        message = "source identities must cover exactly the selected profile versions"
        raise ValueError(message)
    _require_profile_data_action_domain(
        data,
        stable_actions=stable_action_values,
    )
    output_path.write_text(render_version_profiles(data), encoding="utf-8")
    return output_path


def _require_profile_data_action_domain(
    profile_data: Mapping[str, object],
    *,
    stable_actions: Iterable[str],
) -> None:
    expected_actions = tuple(sorted(_stable_action_set(stable_actions)))
    actual_actions = tuple(
        _text_list(
            profile_data.get("stable_actions"),
            label="profile data.stable_actions",
        )
    )
    if actual_actions != expected_actions:
        message = "precompiled profile stable_actions do not match requested actions"
        raise ValueError(message)
    target_versions = tuple(
        _text_list(
            profile_data.get("target_versions"),
            label="profile data.target_versions",
        )
    )
    exact_versions(target_versions, label="profile data.target_versions")
    profiles = _mapping(profile_data.get("profiles"), label="profile data.profiles")
    _require_exact_versions(
        profiles, versions=target_versions, label="profile data.profiles"
    )
    expected_domain = frozenset(expected_actions)
    for version in target_versions:
        profile = _mapping(profiles[version], label=f"profile data.profiles.{version}")
        actions = _mapping(
            profile.get("actions"),
            label=f"profile data.profiles.{version}.actions",
        )
        if frozenset(actions) != expected_domain:
            message = f"profile {version} action domain does not match stable_actions"
            raise ValueError(message)


def require_version_profile_source_anchors(
    source_identities: Mapping[str, Mapping[str, str]],
    *,
    ledger: Mapping[str, object] | None = None,
) -> None:
    """Require generated bundle identities to match reviewed profile anchors."""
    loaded_ledger = (
        load_version_profile_ledger() if ledger is None else copy.deepcopy(dict(ledger))
    )
    sources = _mapping(loaded_ledger.get("sources"), label="ledger.sources")
    for version, raw_identity in source_identities.items():
        if version not in sources:
            message = f"source identity has no exact profile for {version}"
            raise ValueError(message)
        expected = _mapping(sources[version], label=f"ledger.sources.{version}")
        observed = _mapping(raw_identity, label=f"source identity {version}")
        for field in ("tag", "commit", "tree"):
            if observed.get(field) != expected.get(field):
                message = f"version profile {version} source anchor changed at {field}"
                raise ValueError(message)


def _compile_profile(
    version: str,
    *,
    actions: tuple[str, ...],
    ledger: Mapping[str, object],
) -> dict[str, Any]:
    sources = _mapping(ledger["sources"], label="ledger.sources")
    source = copy.deepcopy(
        dict(_mapping(sources[version], label=f"ledger.sources.{version}"))
    )
    metadata_by_version = _mapping(
        ledger["profile_metadata"],
        label="ledger.profile_metadata",
    )
    metadata = _mapping(
        metadata_by_version[version],
        label=f"ledger.profile_metadata.{version}",
    )
    runtime_actions = _materialize_runtime_actions(
        version,
        actions=actions,
        ledger=ledger,
    )
    build_decisions = _compile_build_decisions(
        version,
        runtime_actions=runtime_actions,
        ledger=ledger,
    )
    fingerprints = compute_fingerprints(
        source={
            "provenance": source,
            "semantic_operations": {
                name: decision["fingerprints"]["source"]
                for name, decision in build_decisions.items()
            },
        },
        effective_wire={
            "action_execution_modes": {
                action: capability["execution_mode"]
                for action, capability in runtime_actions.items()
            },
            "semantic_operations": {
                name: decision["fingerprints"]["effective_wire"]
                for name, decision in build_decisions.items()
            },
        },
        consumed_projection={
            name: decision["fingerprints"]["consumed_projection"]
            for name, decision in build_decisions.items()
        },
        preservation={
            name: decision["fingerprints"]["preservation"]
            for name, decision in build_decisions.items()
        },
    )
    return {
        "server_version": version,
        "contract_version": version,
        "family": metadata["family"],
        "support_level": metadata["support_level"],
        "tested": metadata["tested"],
        "source": source,
        "fingerprints": fingerprints,
        "actions": runtime_actions,
        "build_decisions": build_decisions,
    }


def _materialize_runtime_actions(
    version: str,
    *,
    actions: tuple[str, ...],
    ledger: Mapping[str, object],
) -> dict[str, dict[str, str]]:
    profiles = _mapping(ledger["runtime_profiles"], label="ledger.runtime_profiles")
    layers = _list(
        profiles[version],
        label=f"ledger.runtime_profiles.{version}",
    )
    policies = _mapping(ledger["runtime_policies"], label="ledger.runtime_policies")
    groups = _mapping(ledger["action_groups"], label="ledger.action_groups")
    materialized: dict[str, dict[str, str]] = {}
    overridden: set[str] = set()

    for index, raw_layer in enumerate(layers):
        layer = _mapping(
            raw_layer,
            label=f"ledger.runtime_profiles.{version}[{index}]",
        )
        selector = _text(layer.get("selector"), label=f"runtime layer {index}.selector")
        policy_name = _text(
            layer.get("policy"),
            label=f"runtime layer {index}.policy",
        )
        if policy_name not in policies:
            message = f"unknown runtime policy {policy_name!r} for {version}"
            raise ValueError(message)
        policy = cast(
            "dict[str, str]",
            copy.deepcopy(
                dict(
                    _mapping(
                        policies[policy_name],
                        label=f"ledger.runtime_policies.{policy_name}",
                    )
                )
            ),
        )
        if selector == "*":
            if index != 0:
                message = f"runtime profile {version} default must be the first layer"
                raise ValueError(message)
            materialized = {action: copy.deepcopy(policy) for action in actions}
            continue
        if selector not in groups:
            message = f"unknown action group {selector!r} for {version}"
            raise ValueError(message)
        selected_actions = _text_list(
            groups[selector],
            label=f"ledger.action_groups.{selector}",
        )
        duplicate_actions = sorted(overridden.intersection(selected_actions))
        if duplicate_actions:
            message = (
                f"runtime profile {version} overrides actions more than once: "
                f"{', '.join(duplicate_actions)}"
            )
            raise ValueError(message)
        overridden.update(selected_actions)
        for action in selected_actions:
            materialized[action] = copy.deepcopy(policy)

    if set(materialized) != set(actions):
        missing = sorted(set(actions) - set(materialized))
        message = f"runtime profile {version} did not materialize: {', '.join(missing)}"
        raise ValueError(message)
    return {action: materialized[action] for action in actions}


def _compile_build_decisions(
    version: str,
    *,
    runtime_actions: Mapping[str, Mapping[str, Any]],
    ledger: Mapping[str, object],
) -> dict[str, dict[str, Any]]:
    contracts = _mapping(
        ledger["operation_contracts"],
        label="ledger.operation_contracts",
    )
    guards_by_version = _mapping(
        ledger["source_closure_guards"],
        label="ledger.source_closure_guards",
    )
    guards = (
        _mapping(
            guards_by_version[version],
            label=f"ledger.source_closure_guards.{version}",
        )
        if version in guards_by_version
        else {}
    )
    bindings = {
        **READ_OPERATION_BINDINGS[version],
        **RUNTIME_OPERATION_BINDINGS[version],
    }
    decisions: dict[str, dict[str, Any]] = {}
    for semantic_operation in sorted(contracts):
        contract = _mapping(
            contracts[semantic_operation],
            label=f"ledger.operation_contracts.{semantic_operation}",
        )
        stable_action = _text(
            contract.get("stable_action"),
            label=f"operation contract {semantic_operation}.stable_action",
        )
        capability = runtime_actions[stable_action]
        binding = bindings.get(semantic_operation)
        if binding is None:
            decisions[semantic_operation] = _unavailable_build_decision(
                semantic_operation,
                stable_action=stable_action,
                capability=capability,
                contract=contract,
                source_guard=(
                    _text(
                        guards[semantic_operation],
                        label=f"source guard {version}:{semantic_operation}",
                    )
                    if semantic_operation in guards
                    else None
                ),
                version=version,
            )
            continue
        if capability.get("reason") in _TERMINAL_UNAVAILABLE_REASONS:
            message = (
                f"terminal capability {version}:{stable_action} cannot retain "
                f"a runtime binding for {semantic_operation}"
            )
            raise ValueError(message)
        if capability.get("reason") == _WIRE_PRESENT_RUNTIME_LIMITATION and (
            capability.get("availability") != "limited"
            or capability.get("execution_mode") != "not_executable"
        ):
            message = (
                f"runtime limitation {version}:{stable_action} must be "
                "limited and not executable"
            )
            raise ValueError(message)
        fingerprints = _binding_fingerprints(
            semantic_operation,
            binding=binding,
            contract=contract,
            source_guard=(
                _text(
                    guards[semantic_operation],
                    label=f"source guard {version}:{semantic_operation}",
                )
                if semantic_operation in guards
                else None
            ),
        )
        build_status, status_reason = _build_status(
            availability=_text(
                capability.get("availability"),
                label=f"capability {version}:{stable_action}.availability",
            ),
            reason=capability.get("reason"),
        )
        if build_status not in _BUILD_STATUSES:  # pragma: no cover - invariant
            message = f"invalid build status {build_status!r}"
            raise ValueError(message)
        decisions[semantic_operation] = {
            "semantic_operation": semantic_operation,
            "stable_action": stable_action,
            "build_status": build_status,
            "status_reason": status_reason,
            "source_operations": list(binding.source_operations),
            "type_closure": [_wire_type_data(item) for item in binding.type_closure],
            "selector_semantics": [
                _selector_data(item) for item in binding.selector_semantics
            ],
            "evidence_sources": [
                _evidence_data(item) for item in binding.evidence_sources
            ],
            "fingerprints": fingerprints,
            **(
                {"paging_projection": dict(binding.paging_projection)}
                if binding.paging_projection
                else {}
            ),
        }
    return decisions


def _unavailable_build_decision(
    semantic_operation: str,
    *,
    stable_action: str,
    capability: Mapping[str, Any],
    contract: Mapping[str, object],
    source_guard: str | None,
    version: str,
) -> dict[str, Any]:
    """Materialize one reviewed zero-request upstream limitation."""
    availability = _text(
        capability.get("availability"),
        label=f"capability {version}:{stable_action}.availability",
    )
    reason = capability.get("reason")
    if availability not in {"limited", "unsupported"} or (
        reason not in _TERMINAL_UNAVAILABLE_REASONS
    ):
        message = (
            f"operation {version}:{semantic_operation} has no reviewed binding "
            f"but {stable_action} is not terminally unavailable"
        )
        raise ValueError(message)
    if source_guard is not None:
        message = (
            f"unavailable operation {version}:{semantic_operation} cannot have "
            "a source closure guard"
        )
        raise ValueError(message)
    constraint = _text(
        capability.get("constraint"),
        label=f"capability {version}:{stable_action}.constraint",
    )
    evidence_sources = _text_list(
        capability.get("evidence_sources"),
        label=f"capability {version}:{stable_action}.evidence_sources",
    )
    unavailable_contract = {
        "semantic_operation": semantic_operation,
        "availability": availability,
        "reason": reason,
        "constraint": constraint,
        "evidence_sources": evidence_sources,
    }
    fingerprints = compute_fingerprints(
        source={**unavailable_contract, "source_operations": [], "type_closure": []},
        effective_wire={
            **unavailable_contract,
            "execution_mode": "not_executable",
            "wire_policy": contract["wire_policy"],
        },
        consumed_projection=contract["consumed_projection"],
        preservation=contract["preservation"],
    )
    evidence_kind = (
        "upstream_limitation"
        if reason == "upstream_capability_limited"
        else "upstream_absence"
    )
    return {
        "semantic_operation": semantic_operation,
        "stable_action": stable_action,
        "build_status": "blocked",
        "status_reason": reason,
        "source_operations": [],
        "type_closure": [],
        "selector_semantics": [],
        "evidence_sources": [
            {"kind": evidence_kind, "reference": source} for source in evidence_sources
        ],
        "fingerprints": fingerprints,
    }


def _binding_fingerprints(
    semantic_operation: str,
    *,
    binding: ReviewedBinding,
    contract: Mapping[str, object],
    source_guard: str | None,
) -> dict[str, str]:
    source_contract: dict[str, object] = {
        "semantic_operation": semantic_operation,
        "source_operations": list(binding.source_operations),
        "type_closure": [_wire_type_data(item) for item in binding.type_closure],
    }
    effective_wire: dict[str, object] = {
        "semantic_operation": semantic_operation,
        "source_operations": list(binding.source_operations),
        "type_closure": [_wire_type_data(item) for item in binding.type_closure],
        "selector_semantics": [
            _selector_data(item) for item in binding.selector_semantics
        ],
        "wire_policy": contract["wire_policy"],
    }
    if binding.paging_projection:
        projection = dict(binding.paging_projection)
        source_contract["paging_projection"] = projection
        effective_wire["paging_projection"] = projection
    fingerprints = compute_fingerprints(
        source=source_contract,
        effective_wire=effective_wire,
        consumed_projection=contract["consumed_projection"],
        preservation=contract["preservation"],
    )
    if source_guard is not None:
        if _SHA256.fullmatch(source_guard) is None:
            message = f"invalid source closure guard {source_guard!r}"
            raise ValueError(message)
        fingerprints["source"] = source_guard
    return fingerprints


def _wire_type_data(value: WireTypeRef) -> dict[str, object]:
    return asdict(value)


def _selector_data(value: SelectorSemantics) -> dict[str, object]:
    return {
        "resource": value.resource,
        "consumed_selectors": list(value.consumed_selectors),
        "exposed_identities": list(value.exposed_identities),
        "native_identity": value.native_identity,
        "resolution": value.resolution,
        "parent_identity": value.parent_identity,
    }


def _evidence_data(value: EvidenceSource) -> dict[str, object]:
    return asdict(value)


def _build_status(
    *,
    availability: str,
    reason: object,
) -> tuple[str, str]:
    if availability == "supported":
        return ("accepted", "runtime_capability_exists")
    if reason in _TERMINAL_UNAVAILABLE_REASONS or (
        availability == "limited" and reason == _WIRE_PRESENT_RUNTIME_LIMITATION
    ):
        return ("blocked", str(reason))
    return ("pending", "wire_candidate_not_promoted")


def _validate_ledger(
    ledger: Mapping[str, object],
    *,
    stable_actions: frozenset[str],
) -> None:
    if ledger.get("schema_version") != 1:
        message = "version profile ledger schema_version must be 1"
        raise ValueError(message)
    if ledger.get("kind") != "dsctl-version-profile-decision-ledger":
        message = "invalid version profile ledger kind"
        raise ValueError(message)
    versions = reviewed_profile_versions(ledger)
    for field in ("sources", "profile_metadata", "runtime_profiles"):
        values = _mapping(ledger.get(field), label=f"ledger.{field}")
        _require_exact_versions(values, versions=versions, label=f"ledger.{field}")

    _validate_sources(_mapping(ledger["sources"], label="ledger.sources"))
    _validate_metadata(
        _mapping(ledger["profile_metadata"], label="ledger.profile_metadata")
    )
    groups = _mapping(ledger.get("action_groups"), label="ledger.action_groups")
    for name, raw_actions in groups.items():
        actions = _text_list(raw_actions, label=f"ledger.action_groups.{name}")
        unknown = sorted(set(actions) - stable_actions)
        if unknown:
            message = f"action group {name} has unknown actions: {', '.join(unknown)}"
            raise ValueError(message)
        if len(actions) != len(set(actions)):
            message = f"action group {name} contains duplicate actions"
            raise ValueError(message)

    policies = _mapping(
        ledger.get("runtime_policies"),
        label="ledger.runtime_policies",
    )
    for name, raw_policy in policies.items():
        _validate_runtime_policy(
            _mapping(raw_policy, label=f"ledger.runtime_policies.{name}"),
            name=name,
        )
    operation_contracts = _mapping(
        ledger.get("operation_contracts"),
        label="ledger.operation_contracts",
    )
    required_contracts = {
        "identity.current",
        "project.create",
        "project.delete",
        "project.get",
        "project.page",
        "project.update",
        "tenant.create",
        "tenant.delete",
        "tenant.get",
        "tenant.page",
        "tenant.update",
        "workflow.get",
        "workflow.page",
    }
    missing_contracts = sorted(required_contracts - set(operation_contracts))
    if missing_contracts:
        message = (
            "operation contracts are missing established semantic roots: "
            f"{', '.join(missing_contracts)}"
        )
        raise ValueError(message)
    known_semantic_operations = {
        semantic_operation
        for version_bindings in (
            *READ_OPERATION_BINDINGS.values(),
            *RUNTIME_OPERATION_BINDINGS.values(),
        )
        for semantic_operation in version_bindings
    }
    unknown_contracts = sorted(set(operation_contracts) - known_semantic_operations)
    if unknown_contracts:
        message = (
            "operation contracts have no reviewed runtime binding in any exact "
            f"profile: {', '.join(unknown_contracts)}"
        )
        raise ValueError(message)


def _validate_sources(sources: Mapping[str, object]) -> None:
    for version in sources:
        source = _mapping(sources[version], label=f"ledger.sources.{version}")
        if source.get("tag") != version:
            message = f"source tag for {version} must be exact"
            raise ValueError(message)
        for field in ("commit", "tree"):
            value = _text(source.get(field), label=f"source {version}.{field}")
            if _GIT_OBJECT.fullmatch(value) is None:
                message = f"source {version}.{field} must be a full Git object id"
                raise ValueError(message)


def _validate_metadata(metadata: Mapping[str, object]) -> None:
    for version in metadata:
        item = _mapping(
            metadata[version],
            label=f"ledger.profile_metadata.{version}",
        )
        _text(item.get("family"), label=f"profile metadata {version}.family")
        support_level = _text(
            item.get("support_level"),
            label=f"profile metadata {version}.support_level",
        )
        if support_level not in _SUPPORT_LEVELS:
            message = f"invalid support level {support_level!r} for {version}"
            raise ValueError(message)
        if not isinstance(item.get("tested"), bool):
            message = f"profile metadata {version}.tested must be a boolean"
            raise TypeError(message)


def _validate_runtime_policy(policy: Mapping[str, object], *, name: str) -> None:
    availability = _text(
        policy.get("availability"),
        label=f"runtime policy {name}.availability",
    )
    if availability not in _AVAILABILITIES:
        message = f"runtime availability {availability!r} is invalid"
        raise ValueError(message)
    execution_mode = _text(
        policy.get("execution_mode"),
        label=f"runtime policy {name}.execution_mode",
    )
    if execution_mode not in _EXECUTION_MODES:
        message = f"execution mode {execution_mode!r} is invalid"
        raise ValueError(message)
    verification = _text(
        policy.get("verification"),
        label=f"runtime policy {name}.verification",
    )
    if verification not in _VERIFICATIONS:
        message = f"verification {verification!r} is invalid"
        raise ValueError(message)
    if availability == "supported":
        if "constraint" in policy or "reason" in policy:
            message = f"supported runtime policy {name} cannot be constrained"
            raise ValueError(message)
    else:
        _text(policy.get("constraint"), label=f"runtime policy {name}.constraint")
        _text(policy.get("reason"), label=f"runtime policy {name}.reason")
        if execution_mode != "not_executable":
            message = f"fail-closed runtime policy {name} must not be executable"
            raise ValueError(message)
        if policy.get("reason") == _WIRE_PRESENT_RUNTIME_LIMITATION:
            if availability != "limited":
                message = f"runtime limitation policy {name} must be limited"
                raise ValueError(message)
            evidence_sources = policy.get("evidence_sources")
            if not isinstance(evidence_sources, list) or not evidence_sources:
                message = f"runtime limitation policy {name} requires evidence_sources"
                raise ValueError(message)
            _text_list(
                evidence_sources,
                label=f"runtime policy {name}.evidence_sources",
            )


def _require_exact_versions(
    values: Mapping[str, object], *, versions: tuple[str, ...], label: str
) -> None:
    actual = tuple(values)
    if actual != versions:
        missing = sorted(set(versions) - set(actual))
        extra = sorted(set(actual) - set(versions))
        details = []
        if missing:
            details.append(f"missing: {', '.join(missing)}")
        if extra:
            details.append(f"unexpected: {', '.join(extra)}")
        if not details:
            details.append("versions are out of canonical order")
        message = f"{label} must match ledger exact versions ({'; '.join(details)})"
        raise ValueError(message)


def _stable_action_set(values: Iterable[str]) -> frozenset[str]:
    actions = tuple(values)
    if not actions:
        message = "stable_actions must not be empty"
        raise ValueError(message)
    if any(not isinstance(action, str) or not action for action in actions):
        message = "stable_actions must contain non-empty text"
        raise ValueError(message)
    if len(actions) != len(set(actions)):
        message = "stable_actions must not contain duplicates"
        raise ValueError(message)
    return frozenset(actions)


def _fingerprint(value: object) -> str:
    encoded = json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


def _mapping(value: object, *, label: str) -> Mapping[str, Any]:
    if not isinstance(value, dict):
        message = f"{label} must be a JSON object"
        raise TypeError(message)
    if any(not isinstance(key, str) for key in value):
        message = f"{label} keys must be text"
        raise TypeError(message)
    return cast("Mapping[str, Any]", value)


def _list(value: object, *, label: str) -> list[object]:
    if not isinstance(value, list):
        message = f"{label} must be a JSON array"
        raise TypeError(message)
    return value


def _text(value: object, *, label: str) -> str:
    if not isinstance(value, str) or not value:
        message = f"{label} must be non-empty text"
        raise ValueError(message)
    return value


def _text_list(value: object, *, label: str) -> list[str]:
    values = _list(value, label=label)
    if any(not isinstance(item, str) or not item for item in values):
        message = f"{label} must contain non-empty text"
        raise ValueError(message)
    return cast("list[str]", values)


__all__ = [
    "DEFAULT_VERSION_PROFILE_LEDGER",
    "GENERATED_VERSION_PROFILE_PATH",
    "PROFILE_SCHEMA_VERSION",
    "compile_version_profile_data",
    "compute_fingerprints",
    "load_version_profile_ledger",
    "render_version_profiles",
    "require_version_profile_source_anchors",
    "reviewed_profile_versions",
    "write_version_profiles",
]
